#!/bin/sh

if [ $1 != "RECEIVED" ]; then
    exit 0
fi

TEL=$(awk '/^From:/ {print $2}' $2)

if grep -q status $2; then
    echo "To: $TEL" > /tmp/sms
    echo "" >> /tmp/sms
    echo "jeszcze zyje" >> /tmp/sms
        mv /tmp/sms /var/spool/sms/outgoing
fi

    if grep -q reboot $2; then
        reboot
fi

exit 0
